# Generated by Django 4.1.7 on 2023-03-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('ilce', models.CharField(max_length=200)),
                ('il', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
                ('fiyat', models.IntegerField()),
                ('yatak_odasi', models.IntegerField()),
                ('tuvalet', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garaj', models.IntegerField(default=0)),
                ('metre_kare', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('yayin_tarihi', models.DateField()),
                ('emlakci', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
